[package]
name = "aoc2020"
version = "0.1.0"
authors = ["David Szotten <davidszotten@gmail.com>"]
edition = "2018"

[dependencies]
# cached = "*"
clap = "*"
failure = "*"
# itertools = "*"
lazy_static = "*"
# num = "*"
# permutohedron = "*"
# regex = "*"
# md-5 = "*"
